# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(202020)
$foreground = rgb(FFA6A6)
$color0 = rgb(464646)
$color1 = rgb(181818)
$color2 = rgb(221716)
$color3 = rgb(381512)
$color4 = rgb(570F0F)
$color5 = rgb(A00504)
$color6 = rgb(BF0000)
$color7 = rgb(F67777)
$color8 = rgb(AD5353)
$color9 = rgb(202020)
$color10 = rgb(2E1E1E)
$color11 = rgb(4A1C19)
$color12 = rgb(741414)
$color13 = rgb(D50606)
$color14 = rgb(FF0000)
$color15 = rgb(F67777)
