# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(202020)
$foreground = rgb(F4F4F4)
$color0 = rgb(464646)
$color1 = rgb(212121)
$color2 = rgb(474747)
$color3 = rgb(4E4E4E)
$color4 = rgb(565656)
$color5 = rgb(7A7A7A)
$color6 = rgb(A7A7A7)
$color7 = rgb(E6E6E6)
$color8 = rgb(A1A1A1)
$color9 = rgb(2C2C2C)
$color10 = rgb(5E5E5E)
$color11 = rgb(686868)
$color12 = rgb(737373)
$color13 = rgb(A3A3A3)
$color14 = rgb(DFDFDF)
$color15 = rgb(E6E6E6)
