# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(121111)
$foreground = rgb(F8E5B2)
$color0 = rgb(3A393A)
$color1 = rgb(430E08)
$color2 = rgb(392B11)
$color3 = rgb(6B5215)
$color4 = rgb(9A3B0F)
$color5 = rgb(A78119)
$color6 = rgb(B1891A)
$color7 = rgb(EDD288)
$color8 = rgb(A69360)
$color9 = rgb(59130B)
$color10 = rgb(4B3917)
$color11 = rgb(8E6D1C)
$color12 = rgb(CE4F14)
$color13 = rgb(DFAC22)
$color14 = rgb(ECB623)
$color15 = rgb(EDD288)
