source = $HOME/.config/hypr/UserConfigs/01-UserDefaults.conf.conf

# BACKGROUND
background {
    monitor =
    path = $WALLPAPERS_DIR/central_dogma_wallpaper-blured.png
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# Hour-Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
    color = rgba(225, 133, 2, 1.0)
    font_size = 200
    font_family = JetBrainsMono Nerd Font ExtraBold 
    position = -220, -110
    halign = right
    valign = top
}

# Minute-Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = rgba(225, 133, 2, 1.0)
    font_size = 200
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = -220, -380
    halign = right 
    valign = top
}

# Seconds-Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%S")"
    color = rgba(237, 210, 136, 1.0)  # #EDD288
    font_size = 35
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = -350, -390
    halign = right
    valign = top
}

# USER
label {
    monitor =
    text = $USER
    color = rgba(248, 229, 178, 0.8)  # #F8E5B2
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = -335, -260
    halign = right
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    rounding = 12
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    # outer_color = rgba(225, 133, 2, 0.5)
    inner_color = rgba(58, 57, 58, 0.7)   # #3A393A with opacity
    font_color = rgba(248, 229, 178, 1.0) # #F8E5B2
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text =
    hide_input = false
    position = -220, -310
    halign = right
    valign = center
}
